akka {
  stdout-loglevel = DEBUG
  loglevel = DEBUG
  log-config-on-start = off
  actor {
    debug {
      receive = on
      autoreceive = off
      lifecycle = off
      event-stream = off
      unhandled = off
    }
  }
  loggers=["Akka.Logger.Serilog.SerilogLogger, Akka.Logger.Serilog"]
}