akka {
  stdout-loglevel = DEBUG
  loglevel = DEBUG
  log-config-on-start = off
  actor {
    debug {
      receive = on
      autoreceive = on
      lifecycle = on
      event-stream = on
      unhandled = on
    }
  }
  loggers=["Akka.Logger.Serilog.SerilogLogger, Akka.Logger.Serilog"]
}