version: '3.7'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    environment:
      COLLECTOR_OLTP_ENABLED: true
      QUERY_MAX_CLOCK_SKEW_ADJUSTMENT: 1000000000
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
        - "27017:27017"
    volumes:
      - type: bind
        source: ./data
        target: /data/db