version: '3.9'

services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=root
      - MONGODB_INITDB_ROOT_PASSWORD=password
      - MONGO_REPLICA_SET_NAME=rs0
    ports:
      - "27017:27017"
    volumes:
      - type: bind
        source: ./data
        target: /data/db
  mssql:
    container_name: mssql-db
    hostname: mssql-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Passw0rd'
      MSSQL_DATA_DIR: /var/opt/mssql/data
      MSSQL_PID: 'Developer'
      MSSQL_TCP_PORT: 1433
    ports:
      - "1433:1433"
    volumes:
      - ./mssql-data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets
  museum1:
    hostname: museum1
    deploy:
      resources:
        reservations:
          memory: "500mb"
          cpus: "1"
        limits:
          memory: "2gb"
          cpus: "2"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: museum1
    environment:
      APP_UID: "1000"
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__MongoDB: "mongodb://museum_user:NightAtTheMuseum2024!@mongodb:27017/akka"
      ConnectionStrings__SqlServer: "Server=mssql-db;Database=master;User Id=sa;Password=Passw0rd;TrustServerCertificate=True"
      AkkaSettings__ActorSystemName: "AkkaWebApi"
      AkkaSettings__UseClustering: "true"
      AkkaSettings__RemoteOptions__HostName: "museum1" 
      AkkaSettings__RemoteOptions__Port: "8081"
      AkkaSettings__RemoteOptions__MaxFrameSize: "8000000"
      AkkaSettings__ClusterOptions__Roles__0: "root"
      AkkaSettings__ClusterOptions__Roles__1: "root-compute"
      AkkaSettings__ClusterOptions__Roles__2: "compute"
      AkkaSettings__ClusterOptions__Roles__3: "listener"
      AkkaSettings__ShardOptions__StateStoreMode: "persistence"
      AkkaSettings__ShardOptions__RememberEntities: "false"
      AkkaSettings__ShardOptions__Role: "root"
      AkkaSettings__AkkaManagementOptions__Enabled: "true"
      AkkaSettings__AkkaManagementOptions__Hostname: "museum1"
      AkkaSettings__AkkaManagementOptions__PortName: "management"
      AkkaSettings__AkkaManagementOptions__ServiceName: "akka-management"
      AkkaSettings__AkkaManagementOptions__ExternalEndpoints__0: "museum2:8558"
      AkkaSettings__AkkaManagementOptions__ExternalEndpoints__1: "museum3:8558"
      AkkaSettings__AkkaManagementOptions__ExternalEndpoints__2: "museum4:8558"
      AkkaSettings__AkkaManagementOptions__ExternalEndpoints__3: "museum5:8558"
      AkkaSettings__ShardOptions__PassivateIdleEntityAfter: "00:10:00"
      AkkaSettings__ShardOptions__PassivateIdleEntity: "true"
      AkkaSettings__AkkaManagementOptions__RequiredContactPointsNr: "5"
      AkkaSettings__AkkaManagementOptions__DiscoveryMethod: "Config"
      OpenTelemetry__Endpoint: "http://jaeger:4317"
      AkkaSettings__PersistenceMode: "SqlServer"
      SWAGGER_HOST: "http://localhost:8080"
      SEQ: "http://seq:5341"
    ports:
      - "8080:8080"
      - "8081:8081"
      - "9110:9110"
    depends_on:
      - mongodb

  museum2:
    hostname: museum2
    deploy:
      resources:
        reservations:
          memory: "500mb"
          cpus: "1"
        limits:
          memory: "2gb"
          cpus: "2"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: museum2
    environment:
      APP_UID: "1000"
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__MongoDB: "mongodb://museum_user:NightAtTheMuseum2024!@mongodb:27017/akka"
      ConnectionStrings__SqlServer: "Server=mssql-db;Database=master;User Id=sa;Password=Passw0rd;TrustServerCertificate=True"
      AkkaSettings__ActorSystemName: "AkkaWebApi"
      AkkaSettings__UseClustering: "true"
      AkkaSettings__RemoteOptions__HostName: "museum2"
      AkkaSettings__RemoteOptions__Port: "8081"
      AkkaSettings__RemoteOptions__MaxFrameSize: "8000000"
      AkkaSettings__ClusterOptions__Roles__0: "root"
      AkkaSettings__ClusterOptions__Roles__1: "root-compute"
      AkkaSettings__ClusterOptions__Roles__2: "compute"
      AkkaSettings__ShardOptions__StateStoreMode: "persistence"
      AkkaSettings__ShardOptions__RememberEntities: "false"
      AkkaSettings__ShardOptions__Role: "root"
      AkkaSettings__AkkaManagementOptions__Enabled: "true"
      AkkaSettings__AkkaManagementOptions__Hostname: "museum2"
      AkkaSettings__AkkaManagementOptions__PortName: "management"
      AkkaSettings__AkkaManagementOptions__ExternalEndpoints__0: "museum1:8558"
      AkkaSettings__AkkaManagementOptions__ExternalEndpoints__1: "museum3:8558"
      AkkaSettings__AkkaManagementOptions__ExternalEndpoints__2: "museum4:8558"
      AkkaSettings__AkkaManagementOptions__ExternalEndpoints__3: "museum5:8558"
      SEQ: "http://seq:5341"
      AkkaSettings__ShardOptions__PassivateIdleEntityAfter: "00:10:00"
      AkkaSettings__ShardOptions__PassivateIdleEntity: "true"
      AkkaSettings__AkkaManagementOptions__ServiceName: "akka-management"
      AkkaSettings__AkkaManagementOptions__RequiredContactPointsNr: "5"
      AkkaSettings__AkkaManagementOptions__DiscoveryMethod: "Config"
      AkkaSettings__PersistenceMode: "SqlServer"
      OpenTelemetry__Endpoint: "http://jaeger:4317"
      SWAGGER_HOST: "http://localhost:8082"
    ports:
      - "8082:8080"
      - "8083:8081"
      - "9111:9110"
    depends_on:
      - mongodb

  museum3:
    hostname: museum3
    deploy:
      resources:
        reservations:
          memory: "500mb"
          cpus: "1"
        limits:
          memory: "2gb"
          cpus: "2"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: museum3
    environment:
      APP_UID: "1000"
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__MongoDB: "mongodb://museum_user:NightAtTheMuseum2024!@mongodb:27017/akka"
      ConnectionStrings__SqlServer: "Server=mssql-db;Database=master;User Id=sa;Password=Passw0rd;TrustServerCertificate=True"
      AkkaSettings__ActorSystemName: "AkkaWebApi"
      AkkaSettings__UseClustering: "true"
      AkkaSettings__RemoteOptions__HostName: "museum3"
      AkkaSettings__RemoteOptions__Port: "8081"
      AkkaSettings__RemoteOptions__MaxFrameSize: "8000000"
      AkkaSettings__ClusterOptions__Roles__0: "root"
      AkkaSettings__ClusterOptions__Roles__1: "root-compute"
      AkkaSettings__ClusterOptions__Roles__2: "compute"
      AkkaSettings__ShardOptions__StateStoreMode: "persistence"
      AkkaSettings__ShardOptions__RememberEntities: "false"
      AkkaSettings__ShardOptions__Role: "root"
      AkkaSettings__AkkaManagementOptions__Enabled: "true"
      AkkaSettings__AkkaManagementOptions__Hostname: "museum3"
      AkkaSettings__AkkaManagementOptions__PortName: "management"
      AkkaSettings__AkkaManagementOptions__ServiceName: "akka-management"
      AkkaSettings__AkkaManagementOptions__ExternalEndpoints__0: "museum1:8558"
      AkkaSettings__AkkaManagementOptions__ExternalEndpoints__1: "museum2:8558"
      AkkaSettings__AkkaManagementOptions__ExternalEndpoints__2: "museum4:8558"
      AkkaSettings__AkkaManagementOptions__ExternalEndpoints__3: "museum5:8558"
      SEQ: "http://seq:5341"
      AkkaSettings__ShardOptions__PassivateIdleEntityAfter: "00:10:00"
      AkkaSettings__ShardOptions__PassivateIdleEntity: "true"
      AkkaSettings__AkkaManagementOptions__RequiredContactPointsNr: "5"
      AkkaSettings__AkkaManagementOptions__DiscoveryMethod: "Config"
      AkkaSettings__PersistenceMode: "SqlServer"
      OpenTelemetry__Endpoint: "http://jaeger:4317"
      SWAGGER_HOST: "http://localhost:8084"
    ports:
      - "8084:8080"
      - "8085:8081"
      - "9112:9110"
    depends_on:
      - mongodb
  museum4:
    hostname: museum4
    deploy:
      resources:
        reservations:
          memory: "500mb"
          cpus: "1"
        limits:
          memory: "2gb"
          cpus: "2"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: museum4
    environment:
      APP_UID: "1000"
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__MongoDB: "mongodb://museum_user:NightAtTheMuseum2024!@mongodb:27017/akka"
      ConnectionStrings__SqlServer: "Server=mssql-db;Database=master;User Id=sa;Password=Passw0rd;TrustServerCertificate=True"
      AkkaSettings__ActorSystemName: "AkkaWebApi"
      AkkaSettings__UseClustering: "true"
      AkkaSettings__RemoteOptions__HostName: "museum4"
      AkkaSettings__RemoteOptions__Port: "8081"
      AkkaSettings__RemoteOptions__MaxFrameSize: "8000000"
      AkkaSettings__ClusterOptions__Roles__0: "root"
      AkkaSettings__ClusterOptions__Roles__1: "root-compute"
      AkkaSettings__ClusterOptions__Roles__2: "compute"
      AkkaSettings__ShardOptions__StateStoreMode: "persistence"
      AkkaSettings__ShardOptions__RememberEntities: "false"
      AkkaSettings__ShardOptions__Role: "root"
      AkkaSettings__AkkaManagementOptions__Enabled: "true"
      AkkaSettings__AkkaManagementOptions__Hostname: "museum4"
      AkkaSettings__AkkaManagementOptions__PortName: "management"
      AkkaSettings__AkkaManagementOptions__ServiceName: "akka-management"
      AkkaSettings__AkkaManagementOptions__ExternalEndpoints__0: "museum1:8558"
      AkkaSettings__AkkaManagementOptions__ExternalEndpoints__1: "museum2:8558"
      AkkaSettings__AkkaManagementOptions__ExternalEndpoints__2: "museum3:8558"
      AkkaSettings__AkkaManagementOptions__ExternalEndpoints__3: "museum5:8558"
      SEQ: "http://seq:5341"
      AkkaSettings__ShardOptions__PassivateIdleEntityAfter: "00:10:00"
      AkkaSettings__ShardOptions__PassivateIdleEntity: "true"
      AkkaSettings__AkkaManagementOptions__RequiredContactPointsNr: "5"
      AkkaSettings__AkkaManagementOptions__DiscoveryMethod: "Config"
      AkkaSettings__PersistenceMode: "SqlServer"
      OpenTelemetry__Endpoint: "http://jaeger:4317"
      SWAGGER_HOST: "http://localhost:8084"
    ports:
      - "8086:8080"
      - "8087:8081"
      - "9113:9110"
    depends_on:
      - mongodb
  museum5:
    hostname: museum5
    deploy:
      resources:
        reservations:
          memory: "500mb"
          cpus: "1"
        limits:
          memory: "2gb"
          cpus: "2"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: museum5
    environment:
      APP_UID: "1000"
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__MongoDB: "mongodb://museum_user:NightAtTheMuseum2024!@mongodb:27017/akka"
      ConnectionStrings__SqlServer: "Server=mssql-db;Database=master;User Id=sa;Password=Passw0rd;TrustServerCertificate=True"
      AkkaSettings__ActorSystemName: "AkkaWebApi"
      AkkaSettings__UseClustering: "true"
      AkkaSettings__RemoteOptions__HostName: "museum5"
      AkkaSettings__RemoteOptions__Port: "8081"
      AkkaSettings__RemoteOptions__MaxFrameSize: "8000000"
      AkkaSettings__ClusterOptions__Roles__0: "root"
      AkkaSettings__ClusterOptions__Roles__1: "root-compute"
      AkkaSettings__ClusterOptions__Roles__2: "compute"
      AkkaSettings__ShardOptions__StateStoreMode: "persistence"
      AkkaSettings__ShardOptions__RememberEntities: "false"
      AkkaSettings__ShardOptions__Role: "root"
      AkkaSettings__AkkaManagementOptions__Enabled: "true"
      AkkaSettings__AkkaManagementOptions__Hostname: "museum5"
      AkkaSettings__AkkaManagementOptions__PortName: "management"
      AkkaSettings__AkkaManagementOptions__ServiceName: "akka-management"
      AkkaSettings__AkkaManagementOptions__ExternalEndpoints__0: "museum1:8558"
      AkkaSettings__AkkaManagementOptions__ExternalEndpoints__1: "museum2:8558"
      AkkaSettings__AkkaManagementOptions__ExternalEndpoints__2: "museum3:8558"
      AkkaSettings__AkkaManagementOptions__ExternalEndpoints__3: "museum4:8558"
      AkkaSettings__ShardOptions__PassivateIdleEntityAfter: "00:10:00"
      AkkaSettings__ShardOptions__PassivateIdleEntity: "true"
      AkkaSettings__AkkaManagementOptions__RequiredContactPointsNr: "5"
      AkkaSettings__AkkaManagementOptions__DiscoveryMethod: "Config"
      AkkaSettings__PersistenceMode: "SqlServer"
      OpenTelemetry__Endpoint: "http://jaeger:4317"
      SEQ: "http://seq:5341"
      SWAGGER_HOST: "http://localhost:8084"
    ports:
      - "8088:8080"
      - "8089:8081"
      - "9114:9110"
    depends_on:
      - mongodb
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    environment:
      COLLECTOR_OLTP_ENABLED: true
      QUERY_MAX_CLOCK_SKEW_ADJUSTMENT: 1000000000
      
  # SEQ Log Server
  seq:
    hostname: seq
    image: datalust/seq:latest
    volumes:
      - ./seq-data:/data
    ports:
      - "8020:80"
      - "5341:5341"
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD="Password123!"